### ISSUE TITLE
Upgrading from Greebo to Hogfather, tabs are not displayed any more

### ISSUE THREAD

**Issue by roadrunnerjb** [cosmocode/dokuwiki-plugin-tabbox#14]
Hi,

We have two wiki instances up and running. The first we updated some weeks ago. Now the second is in the line.
I did a clone of this dokuwiki instance. Updated this instance. After reinstalling updating the plugins the page seemd to work well. Not too much messages in apaches error.log only some PHP Warnings but nothing related to thee tabbox plugin.

While Testing I saw that all pages using tabbox plugin don't show tab's.Instead the content is rendered sequentially as described in the plugin's docu . I checked different browsers Chrome/edge and Firefox but always the same. 

The old wiki is still working and tab's are show correctly so no browser issue. The first (already upgraded) wiki is also working with tabs. So in general tabbox seems to be working with Hogfather but I'm guessing where the problem is.

Is it possible that another plugin interferes with tabbox plugin ? Or what else can I check to get forward with this upgrade ?

Any Ideas are welcome...

**Comment by petham07** [comment]
Hi,

I encoutered the same error with Tabbox at the upgrade to Hogfather. Instead of inline tabs a bullet column is shown.

**Comment by platsch** [comment]
Same problem here. Running Hogfather and Bootstrap3.
Seems to be a compatibility issue with Bootstrap template, if I switch back to dokuwiki template, it works.

Also see this issue: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues/530

Any chance this could be fixed anytime soon? I already started to investigate a bit deeper, but I'm not a web developer.

**Comment by platsch** [comment]
Solved in the bootstrap template: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/commit/9d5a31b267b7e3d539db0d3d23f76a145cac0085
