### ISSUE TITLE
Error "startSectionEdit: $data "section" is NOT an array!" after Greebo update

### ISSUE THREAD

**Issue by jakob1111** [cosmocode/dokuwiki-plugin-tabbox#5]
On every page with tabboxes now the message

"startSectionEdit: $data "section" is NOT an array! One of your plugins needs an update." appears.

While fixes exist for other affected plugins, like the include and wrap plugin, no fix for the tabbox plugin exists yet.

C.f. https://github.com/dokufreaks/plugin-include/issues/223 and https://github.com/selfthinker/dokuwiki_plugin_wrap/pull/162

**Comment by splitbrain** [comment]
pull requests welcome

**Comment by martk70** [comment]
I endorse jakob1111's observation! 
My added request is: Would a pro perhaps be so kind as to spent some time on this and update this invaluable plugin?!
I don't know how to _pull_ this request, but I hope this helps!

**Comment by chrissommer** [comment]
+1 with this problem :)

**Comment by hongsoog** [comment]
I have updated all the installed plugins but the problem not solved.

**Comment by asheenlevrai** [comment]
What plugin causes this message? Isn't it EditSection2 (not maintained anymore)?
